export const SPIDER_MODULES_CONFIG = [
  {
    id: 'dir_bruteforce',
    title: 'Брутфорс директорий',
    desc: 'Поиск скрытых папок и файлов (например: /admin, /backup, /config). Помогает найти скрытые панели управления.',
  },
  {
    id: 'enable_vuln_verification',
    title: 'Сверка с базами CVE',
    desc: 'Анализ версии прошивки и поиск известных уязвимостей (например, обход авторизации в старых Hikvision).',
  },
  {
    id: 'enable_video_stream_analyzer',
    title: 'Анализ видеопотока',
    desc: 'Извлечение метаданных камеры через ffprobe (кодек, битрейт, FPS, разрешение) без фактической записи видео.',
  },
  {
    id: 'enable_passive_arp_discovery',
    title: 'Пассивный ARP-скан',
    desc: 'Поиск скрытых устройств в локальной сети на основе ARP-таблицы (MAC-адреса).',
  },
  {
    id: 'enable_credential_depth_audit',
    title: 'Аудит учетных записей',
    desc: 'Безопасная проверка использования стандартных заводских или слабых паролей (admin:admin, admin:12345).',
  },
  {
    id: 'enable_open_share_scanner',
    title: 'Сканер открытых шар (FTP)',
    desc: 'Проверка наличия анонимного доступа к файловой системе камеры или регистратора.',
  },
  {
    id: 'enable_osint_import',
    title: 'OSINT обогащение',
    desc: 'Сбор информации об IP-адресе из внешних баз данных и открытых поисковиков.',
  },
  {
    id: 'enable_topology_discovery',
    title: 'Топология сети',
    desc: 'Построение карты связей между устройствами (требует активный ONVIF/CGI профиль).',
  },
  {
    id: 'enable_threat_intel',
    title: 'Threat Intelligence',
    desc: 'Прикрепление к отчету ссылок на известные эксплойты и официальные бюллетени безопасности для данного вендора.',
  },
];

export const createSpiderSlice = (set) => ({
  spiderTarget: import.meta.env.VITE_DEFAULT_SPIDER_TARGET || '',
  spiderMaxDepth: 3,
  spiderMaxPages: 50,
  spiderDirBrute: true,
  spiderEnableVulnVerification: false,
  spiderEnableOsintImport: false,
  spiderEnableTopologyDiscovery: false,
  spiderEnableSnapshotRefresh: false,
  spiderEnableVideoStreamAnalyzer: false,
  spiderEnableCredentialDepthAudit: false,
  spiderEnablePassiveArpDiscovery: false,
  spiderEnableUptimeMonitoring: false,
  spiderEnableNeighborDiscovery: false,
  spiderEnableThreatIntel: false,
  spiderEnableScheduledAudits: false,
  spiderRunning: false,
  spiderReport: null,
  spiderTab: 'pages',

  setSpiderTarget: (v) => set({ spiderTarget: v }),
  setSpiderMaxDepth: (v) => set({ spiderMaxDepth: v }),
  setSpiderMaxPages: (v) => set({ spiderMaxPages: v }),
  setSpiderDirBrute: (v) => set({ spiderDirBrute: v }),
  setSpiderEnableVulnVerification: (v) => set({ spiderEnableVulnVerification: v }),
  setSpiderEnableOsintImport: (v) => set({ spiderEnableOsintImport: v }),
  setSpiderEnableTopologyDiscovery: (v) => set({ spiderEnableTopologyDiscovery: v }),
  setSpiderEnableSnapshotRefresh: (v) => set({ spiderEnableSnapshotRefresh: v }),
  setSpiderEnableVideoStreamAnalyzer: (v) => set({ spiderEnableVideoStreamAnalyzer: v }),
  setSpiderEnableCredentialDepthAudit: (v) => set({ spiderEnableCredentialDepthAudit: v }),
  setSpiderEnablePassiveArpDiscovery: (v) => set({ spiderEnablePassiveArpDiscovery: v }),
  setSpiderEnableUptimeMonitoring: (v) => set({ spiderEnableUptimeMonitoring: v }),
  setSpiderEnableNeighborDiscovery: (v) => set({ spiderEnableNeighborDiscovery: v }),
  setSpiderEnableThreatIntel: (v) => set({ spiderEnableThreatIntel: v }),
  setSpiderEnableScheduledAudits: (v) => set({ spiderEnableScheduledAudits: v }),
  setSpiderRunning: (v) => set({ spiderRunning: v }),
  setSpiderReport: (v) => set({ spiderReport: v }),
  setSpiderTab: (v) => set({ spiderTab: v }),
});
